version: 2.1
orbs:
  # Choose either one of the orbs below
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name infra \
                --region us-east-1
  config_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            fingerprint: ["94:62:e8:7a:8f:27:79:e3:cd:78:a0:31:a2:95:57:56"] 
        - run:
            name: install ansible
            command: |
              apk add --update ansible
        - run:
            name: configure
            command: |
              ansible-playbook -i inventory playbook.yml
workflows:
  my_workflow:
      jobs:
        - create_infrastructure     
        - config_infrastructure           