version: 2.1
# orbs:
#   # Choose either one of the orbs below
#   # Declare a dependency on the welcome-orb
#   # welcome: circleci/welcome-orb@0.4.1
#   aws-cli: circleci/aws-cli@2.0.3
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name infra2 \
                --region us-east-1
  config_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            fingerprint: ["54:e5:4c:65:d7:6c:a4:42:bf:b1:e2:08:4f:e8:f9:70"] 
        - run:
            name: install ansible
            command: |
              apk add --update ansible
        - run:
            name: configure
            command: |
              ansible-playbook -i inventory playbook.yml
workflows:
  my_workflow:
      jobs:
        # - create_infrastructure     
        - config_infrastructure           